### PR TITLE
Changed Api Source

### LINKED ISSUE #2: Omdb api not working anymore
As omdbapi is not working anymore, add another api which fetch details for movies.
Help : "http://theapache64.xyz:8080/movie_db/search?keyword="+id" , will work.

Implement in the code accordingly.
Anyone can contribute!

### PR DESCRIPTION
**Pull request by thiefsheep**
Fixes #2 
cheerio 🎉.

### CODE REVIEW

**Comment by bodhwani** [comment]
Thanx @thiefsheep for your contribution.
Have you tried to run this?
We will recieve "data" as a dictionary, in which we will get as :
 {
'error_code',
'message',
'data':{},
'error'
}
and all the details like plot, imdb_id, genre etc are inside data. So it can be accessed by data["data"]["genre"].
Please change your code and try to make it in running.

**Comment by thiefsheep** [comment]
My mistake  :sweat_smile:

**Comment by bodhwani** [comment]
values in dictionary cannot be accessed as data.data.genre.
It is AttributeError: 'dict' object has no attribute 'data'

Try for data["data"]["genre"].

**Comment by bodhwani** [comment]
@thiefsheep  There is an error in data.error_code. Same concept as mentioned before.
I request you to check if code is working fine by running it. Do not make Pr without running it.

**Pull request closed without merging**
